Fix build error by using floats in qMin comparison
*sample is of type float, which caused fabs to return float.

widget.cpp:407:41: error: no matching function for call to ‘qMin(double, float)’
         value = qMin(1.00, fabs(*sample)) * alpha;